### PR TITLE
[IMP] medical_diagnostic_report: add readme

### PR DESCRIPTION
**Pull request by albariera**

### CODE REVIEW

**Comment by albariera** [comment]
I have done cherry-pick of this commit at #142

**Comment by ghost** [comment]
Congratulations, PR rebased to [13.0](https://github.com/tegin/medical-fhir/commits/13.0).

**Comment by ghost** [comment]
Hi @etobella. Your command failed:

``Invalid command: add_psc``.

**Ocabot commands**
* ``ocabot merge major|minor|patch|nobump``
* ``ocabot rebase``
* ``ocabot migration {MODULE_NAME}``

**More information**
 * [ocabot documentation](https://github.com/OCA/oca-github-bot/#commands)
 * [OCA guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst), specially the "Version Numbers" section.

**Pull request closed without merging**
